[build]
  command = "npm run build"
  publish = "frontend/build"
  functions = "netlify-functions"

[dev]
  command = "npm run dev" # This should start your React/Vite server
  targetPort = 5174       # Port your frontend runs on
  port = 8888             # Netlify Dev's own server port (change if 8888 is in use)

[[redirects]]
  from = "/api/*"
  to = "http://localhost:9090/:splat"
  status = 200
  force = true  # This line is crucial as it tells Netlify to proxy the request instead of redirecting

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200